import type { Handler } from "@netlify/functions";
import { requireSession } from "./_auth";
import { supabaseAdmin } from "./_supabase";
import { badRequest, json, unauthorized } from "./_shared";

/**
 * Sends a full-detail EOD email (no photos) for the whole team for a given date (defaults to today).
 * Uses RESEND_API_KEY + RESEND_FROM_EMAIL.
 */
function ymd(d: Date) {
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

export const handler: Handler = async (event) => {
  try {
    if (event.httpMethod !== "POST") return json({ ok: false, error: "Method not allowed" }, 405);

    const session = await requireSession(event);
    if (!session) return unauthorized();

    const body = event.body ? JSON.parse(event.body) : {};
    const report_date = String(body.report_date || "").trim(); // YYYY-MM-DD
    const notes = String(body.notes || "");
    const handoff_notes = String(body.handoff_notes || "");

    const date = report_date ? new Date(report_date + "T00:00:00") : new Date();
    const day = ymd(date);

    const supabase = supabaseAdmin();

    // Collect team-wide data for the day
    const start = new Date(day + "T00:00:00").toISOString();
    const end = new Date(day + "T23:59:59.999").toISOString();

    const [tickets, ticketComments, projects, projectComments, runs, runSteps, employees] = await Promise.all([
      supabase.from("tickets").select("*").gte("created_at", start).lte("created_at", end),
      supabase.from("ticket_comments").select("*").gte("created_at", start).lte("created_at", end),
      supabase.from("projects").select("*").gte("created_at", start).lte("created_at", end),
      supabase.from("project_comments").select("*").gte("created_at", start).lte("created_at", end),
      supabase.from("procedure_runs").select("*").gte("started_at", start).lte("started_at", end),
      supabase.from("procedure_run_steps").select("*"),
      supabase.from("employees").select("id, name, employee_id, email"),
    ]);

    const snapshot = {
      day,
      generated_at: new Date().toISOString(),
      generated_by: session.employee,
      tickets: tickets.data || [],
      ticket_comments: ticketComments.data || [],
      projects: projects.data || [],
      project_comments: projectComments.data || [],
      procedure_runs: runs.data || [],
      procedure_run_steps: runSteps.data || [],
      employees: employees.data || [],
      notes,
      handoff_notes,
    };

    // Build email HTML (simple MVP)
    const subject = `EOD Report – ${day} – Maintenance`;
    const html = `
      <div style="font-family: Arial, sans-serif; line-height: 1.4">
        <h2>${subject}</h2>
        <p><b>Generated by:</b> ${session.employee.name} (${session.employee.employee_id})</p>
        <p><b>Generated at:</b> ${new Date().toLocaleString()}</p>
        <hr/>
        <h3>Notes</h3>
        <pre style="white-space: pre-wrap">${escapeHtml(notes)}</pre>
        <h3>Handoff Notes</h3>
        <pre style="white-space: pre-wrap">${escapeHtml(handoff_notes)}</pre>
        <hr/>
        <h3>Procedures</h3>
        ${listProcedures(snapshot)}
        <hr/>
        <h3>Tickets</h3>
        ${listTickets(snapshot)}
        <hr/>
        <h3>Projects</h3>
        ${listProjects(snapshot)}
      </div>
    `;

    // Send email via Resend
    const apiKey = process.env.RESEND_API_KEY;
    const from = process.env.RESEND_FROM_EMAIL;
    if (!apiKey || !from) return badRequest("Email not configured (RESEND_API_KEY/RESEND_FROM_EMAIL)");

    const to = session.employee.email;

    const sendRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "authorization": `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        from,
        to,
        subject,
        html,
      }),
    });

    let email_status = "sent";
    let email_error: string | null = null;
    if (!sendRes.ok) {
      email_status = "failed";
      email_error = await sendRes.text();
    }

    // Save report snapshot
    await supabase.from("end_of_day_reports").insert({
      report_date: day,
      created_by: session.employee.id,
      notes,
      handoff_notes,
      snapshot_json: snapshot,
      emailed_to: to,
      email_status,
      email_error,
    });

    if (email_status === "failed") return json({ ok: false, error: "Email send failed", detail: email_error }, 502);

    return json({ ok: true, emailed_to: to });
  } catch (e: any) {
    return json({ ok: false, error: e?.message || "Server error" }, 500);
  }
};

function escapeHtml(s: string) {
  return (s || "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function empName(snapshot: any, empId: string) {
  const e = (snapshot.employees || []).find((x: any) => x.id === empId);
  return e ? e.name : empId;
}

function listProcedures(snapshot: any) {
  const runs = snapshot.procedure_runs || [];
  if (!runs.length) return "<p>No procedure runs logged.</p>";
  return "<ul>" + runs.map((r: any) => {
    const who = empName(snapshot, r.performed_by);
    const started = new Date(r.started_at).toLocaleString();
    const completed = r.completed_at ? new Date(r.completed_at).toLocaleString() : "—";
    const dur = r.duration_seconds != null ? `${r.duration_seconds}s` : "—";
    return `<li><b>${r.procedure_id}</b> — ${who} — start: ${started} — end: ${completed} — duration: ${dur}</li>`;
  }).join("") + "</ul>";
}

function listTickets(snapshot: any) {
  const tickets = snapshot.tickets || [];
  if (!tickets.length) return "<p>No tickets created today.</p>";

  const comments = snapshot.ticket_comments || [];
  return tickets.map((t: any) => {
    const who = empName(snapshot, t.created_by);
    const created = new Date(t.created_at).toLocaleString();
    const due = new Date(t.sla_due_at).toLocaleString();
    const tComments = comments.filter((c: any) => c.ticket_id === t.id);
    return `
      <div style="padding:12px;border:1px solid #ddd;border-radius:10px;margin:10px 0">
        <div><b>${escapeHtml(t.title)}</b></div>
        <div>Location: ${escapeHtml(t.location)}</div>
        <div>Created: ${created} by ${escapeHtml(who)}</div>
        <div>SLA Due: ${due}</div>
        <div>Status: ${escapeHtml(t.status)}</div>
        <div style="margin-top:8px"><b>Comments</b></div>
        ${tComments.length ? "<ul>" + tComments.map((c: any) => {
          const cn = empName(snapshot, c.employee_id);
          const ct = new Date(c.created_at).toLocaleString();
          return `<li>${ct} — ${escapeHtml(cn)}: ${escapeHtml(c.comment)}</li>`;
        }).join("") + "</ul>" : "<div>No comments.</div>"}
      </div>
    `;
  }).join("");
}

function listProjects(snapshot: any) {
  const projects = snapshot.projects || [];
  if (!projects.length) return "<p>No projects created today.</p>";

  const comments = snapshot.project_comments || [];
  return projects.map((p: any) => {
    const who = empName(snapshot, p.created_by);
    const created = new Date(p.created_at).toLocaleString();
    const due = new Date(p.sla_due_at).toLocaleString();
    const pComments = comments.filter((c: any) => c.project_id === p.id);
    return `
      <div style="padding:12px;border:1px solid #ddd;border-radius:10px;margin:10px 0">
        <div><b>${escapeHtml(p.title)}</b></div>
        <div>Location: ${escapeHtml(p.location)}</div>
        <div>Created: ${created} by ${escapeHtml(who)}</div>
        <div>Due: ${due}</div>
        <div>Status: ${escapeHtml(p.status)}</div>
        <div style="margin-top:8px"><b>Comments</b></div>
        ${pComments.length ? "<ul>" + pComments.map((c: any) => {
          const cn = empName(snapshot, c.employee_id);
          const ct = new Date(c.created_at).toLocaleString();
          return `<li>${ct} — ${escapeHtml(cn)}: ${escapeHtml(c.comment)}</li>`;
        }).join("") + "</ul>" : "<div>No comments.</div>"}
      </div>
    `;
  }).join("");
}
